using System;
using UnityEngine;

namespace DampedPendulumLab
{
    /// Small-angle viscous damping, released from rest. SI units, root-local geometry.
    public sealed class DampedPendulumExperiment : MonoBehaviour
    {
        public const float BoardTop = 0.129f, Travel = 0.24f, BoardStartZ = -0.12f;
        public const float EquilibriumBobY = 0.20f, BobRadius = 0.02f;
        [Header("Apply parameters with ResetExperiment")]
        [Range(0.3f, 0.7f)] public float pendulumLength = 0.48f;
        [Range(0f, 10f)] public float initialAngleDegrees = 10f;
        [Range(0f, 0.8f)] public float dampingRate = 0.12f;
        [Range(1f, 20f)] public float gravity = 9.81f;
        [Range(0.005f, 0.04f)] public float boardSpeed = 0.02f;
        [Range(0f, 3f)] public float playbackSpeed = 1f;
        public bool playOnAwake = true;
        [Header("Generated references")]
        public Transform supportPost, topArm, pivot, cord, bob, markerBody, markerNib;
        public Transform boardCarriage, motorRotor;
        public float AngleRadians { get; private set; }
        public float AngularVelocity { get; private set; }
        public float ElapsedSeconds { get { return (float)elapsed; } }
        public float TravelProgress { get { return Mathf.Clamp01((float)(elapsed * activeSpeed / Travel)); } }
        public float DampedPeriod { get { return (float)(2.0 * Math.PI / wd); } }
        public bool IsRunning { get; private set; }
        public bool IsComplete { get; private set; }
        public Vector3 LocalPenContact { get; private set; }
        double elapsed, wd = 4.519, w0Squared, beta, theta0;
        float activeLength = 0.48f, activeSpeed = 0.02f;

        void Awake()
        {
            if (!supportPost || !topArm || !pivot || !cord || !bob || !markerBody || !markerNib || !boardCarriage || !motorRotor)
            { Debug.LogError("Use the prefab generated by Tools > Damped Pendulum Lab.", this); enabled = false; return; }
            ResetExperiment();
            IsRunning = playOnAwake;
        }
        void Update()
        {
            if (!IsRunning) return;
            elapsed = Math.Min(Travel / activeSpeed, elapsed + Time.deltaTime * Mathf.Max(0f, playbackSpeed));
            ApplyPose();
            if (elapsed >= Travel / activeSpeed) { IsComplete = true; IsRunning = false; }
        }
        public void Play() { if (!IsComplete) IsRunning = true; }
        public void Pause() { IsRunning = false; }
        public void RestartAndPlay() { ResetExperiment(); IsRunning = true; }
        public void SetDamping(float value) { dampingRate = value; ResetExperiment(); }
        public void SetBoardSpeed(float value) { boardSpeed = value; ResetExperiment(); }
        public void SetLength(float value) { pendulumLength = value; ResetExperiment(); }
        public void SetInitialAngle(float value) { initialAngleDegrees = value; ResetExperiment(); }
        public void ResetExperiment()
        {
            IsRunning = false; IsComplete = false; elapsed = 0.0;
            activeLength = Mathf.Clamp(pendulumLength, 0.3f, 0.7f);
            activeSpeed = Mathf.Clamp(boardSpeed, 0.005f, 0.04f);
            w0Squared = Mathf.Clamp(gravity, 1f, 20f) / activeLength;
            beta = Math.Min(Mathf.Clamp(dampingRate, 0f, 0.8f), 0.75 * Math.Sqrt(w0Squared));
            wd = Math.Sqrt(w0Squared - beta * beta);
            theta0 = Mathf.Clamp(initialAngleDegrees, 0f, 10f) * Math.PI / 180.0;
            ApplyPose();
        }
        public void SeekSeconds(float seconds)
        {
            IsRunning = false;
            elapsed = Mathf.Clamp(seconds, 0f, Travel / activeSpeed);
            IsComplete = elapsed >= Travel / activeSpeed;
            ApplyPose();
        }
        void ApplyPose()
        {
            if (!bob || !cord || !boardCarriage) return;
            double sine = Math.Sin(wd * elapsed), cosine = Math.Cos(wd * elapsed);
            double decay = Math.Exp(-beta * elapsed);
            // This form satisfies alpha(0)=alpha0 and alpha'(0)=0.
            AngleRadians = (float)(theta0 * decay * (cosine + beta / wd * sine));
            AngularVelocity = (float)(-theta0 * decay * w0Squared / wd * sine);
            Vector3 pivotPosition = new Vector3(0f, EquilibriumBobY + activeLength, 0f);
            Vector3 down = new Vector3(Mathf.Sin(AngleRadians), -Mathf.Cos(AngleRadians), 0f);
            Vector3 center = pivotPosition + activeLength * down;
            pivot.localPosition = pivotPosition;
            float postBottom = 0.06f, postTop = pivotPosition.y + 0.016f;
            supportPost.localPosition = new Vector3(0f, (postBottom + postTop) * 0.5f, 0.53f);
            supportPost.localScale = new Vector3(0.012f, (postTop - postBottom) * 0.5f, 0.012f);
            topArm.localPosition = new Vector3(0f, postTop, 0.25f);
            topArm.localScale = new Vector3(0.065f, 0.024f, 0.59f);
            bob.localPosition = center;
            cord.localPosition = pivotPosition + down * ((activeLength - BobRadius) * 0.5f);
            cord.localRotation = Quaternion.FromToRotation(Vector3.up, down);
            cord.localScale = new Vector3(0.0018f, (activeLength - BobRadius) * 0.5f, 0.0018f);
            // Simplified vertical follower: short sliding nib keeps contact as bob rises.
            Vector3 bodyTop = center + Vector3.down * 0.018f;
            Vector3 bodyBottom = center + Vector3.down * 0.052f;
            LocalPenContact = new Vector3(center.x, BoardTop, 0f);
            Segment(markerBody, bodyTop, bodyBottom, 0.006f);
            Segment(markerNib, bodyBottom, LocalPenContact, 0.0025f);
            boardCarriage.localPosition = new Vector3(0f, 0f, BoardStartZ + (float)(activeSpeed * elapsed));
            // Roller radius 12 mm; marker rotates to make the drive visible.
            motorRotor.localRotation = Quaternion.Euler(0f, 0f, (float)(-activeSpeed * elapsed / 0.012 * 180.0 / Math.PI));
        }
        static void Segment(Transform part, Vector3 a, Vector3 b, float diameter)
        {
            Vector3 delta = b-a;
            part.localPosition = (a+b)*0.5f;
            part.localRotation = Quaternion.FromToRotation(Vector3.up, delta);
            part.localScale = new Vector3(diameter, delta.magnitude*0.5f, diameter);
        }
        public void PreparePreview() { ResetExperiment(); }
    }
}
